### ISSUE TITLE
pip install no longer works...

### ISSUE THREAD

**Issue by bschroeter** [CABLE-LSM/benchcab#187]
Just tried to install on Gadi for local development with `pip install -e .` in the root directory and get the following error:

```
(benchcab-dev) pip install -e .
Traceback (most recent call last):
  File "/g/data/v14/REDACTED/apps/miniconda3/envs/benchcab-dev/bin/pip", line 6, in <module>
    from pip._internal.cli.main import main
  File "/g/data/v14/REDACTED/apps/miniconda3/envs/benchcab-dev/lib/python3.9/site-packages/pip/_internal/cli/main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/g/data/v14/REDACTED/apps/miniconda3/envs/benchcab-dev/lib/python3.9/site-packages/pip/_internal/cli/autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/g/data/v14/REDACTED/apps/miniconda3/envs/benchcab-dev/lib/python3.9/site-packages/pip/_internal/cli/main_parser.py", line 9, in <module>
    from pip._internal.build_env import get_runnable_pip
  File "/g/data/v14/REDACTED/apps/miniconda3/envs/benchcab-dev/lib/python3.9/site-packages/pip/_internal/build_env.py", line 19, in <module>
    from pip._internal.cli.spinners import open_spinner
  File "/g/data/v14/REDACTED/apps/miniconda3/envs/benchcab-dev/lib/python3.9/site-packages/pip/_internal/cli/spinners.py", line 9, in <module>
    from pip._internal.utils.logging import get_indentation
  File "/g/data/v14/REDACTED/apps/miniconda3/envs/benchcab-dev/lib/python3.9/site-packages/pip/_internal/utils/logging.py", line 29, in <module>
    from pip._internal.utils.misc import ensure_dir
  File "/g/data/v14/REDACTED/apps/miniconda3/envs/benchcab-dev/lib/python3.9/site-packages/pip/_internal/utils/misc.py", line 43, in <module>
    from pip._internal.exceptions import CommandError, ExternallyManagedEnvironment
  File "/g/data/v14/REDACTED/apps/miniconda3/envs/benchcab-dev/lib/python3.9/site-packages/pip/_internal/exceptions.py", line 18, in <module>
    from pip._vendor.requests.models import Request, Response
  File "/g/data/v14/REDACTED/apps/miniconda3/envs/benchcab-dev/lib/python3.9/site-packages/pip/_vendor/requests/__init__.py", line 43, in <module>
    from pip._vendor import urllib3
  File "/g/data/v14/REDACTED/apps/miniconda3/envs/benchcab-dev/lib/python3.9/site-packages/pip/_vendor/urllib3/__init__.py", line 13, in <module>
    from .connectionpool import HTTPConnectionPool, HTTPSConnectionPool, connection_from_url
  File "/g/data/v14/REDACTED/apps/miniconda3/envs/benchcab-dev/lib/python3.9/site-packages/pip/_vendor/urllib3/connectionpool.py", line 12, in <module>
    from .connection import (
  File "/g/data/v14/REDACTED/apps/miniconda3/envs/benchcab-dev/lib/python3.9/site-packages/pip/_vendor/urllib3/connection.py", line 15, in <module>
    from .util.proxy import create_proxy_ssl_context
  File "/g/data/v14/REDACTED/apps/miniconda3/envs/benchcab-dev/lib/python3.9/site-packages/pip/_vendor/urllib3/util/__init__.py", line 8, in <module>
    from .ssl_ import (
  File "/g/data/v14/REDACTED/apps/miniconda3/envs/benchcab-dev/lib/python3.9/site-packages/pip/_vendor/urllib3/util/ssl_.py", line 17, in <module>
    from .url import BRACELESS_IPV6_ADDRZ_RE, IPV4_RE
ValueError: source code string cannot contain null bytes
```

Does a pip install no longer work? Is there a preferred method to install on Gadi?

**Comment by SeanBryan51** [comment]
I was able to pip install successfully with `module load conda && conda activate benchcab-dev && pip install --user .`. Although from looking at your output, it looks like the location of your `benchcab-dev` environment is different to mine: when I run `which python` while the environment is activated outputs `/scratch/tm70/sb8430/conda/envs/benchcab-dev/bin/python`. It could be worth trying to setup the environment again, to create a custom conda environment I follow the instructions [here](http://climate-cms.wikis.unsw.edu.au/Conda#Creating_personal_environments)

**Comment by bschroeter** [comment]
Yes, you are correct. I do use a custom conda installation. However, I have never had any issues with it before. I'll see what I can do. Thanks for your help

**Comment by bschroeter** [comment]
I still had issues with this when installing from "base nothing" - put together a reproducible example of the failures and update this issue.
