### ISSUE TITLE
Not working when svn password not saved

### ISSUE THREAD

**Issue by ccarouge** [CABLE-LSM/benchcab#2]
When retrieving the source code from the svn repository, if the user hasn't saved their password for svn, the code crashes.

```
Retrieving the source code from both branches in the src/ directory
Password:
Traceback (most recent call last):
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-22.04/bin/benchcab", line 10, in <module>
    sys.exit(main_argv())
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-22.04/lib/python3.9/site-packages/benchcab/benchcab.py", line 195, in main_argv
    mess = main_parse_args(sys.argv[1:])
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-22.04/lib/python3.9/site-packages/benchcab/benchcab.py", line 189, in main_parse_args
    return main(parse_args(arglist))
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-22.04/lib/python3.9/site-packages/benchcab/benchcab.py", line 135, in main
    retrieve_cable_code(benchdirs, opt)
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-22.04/lib/python3.9/site-packages/benchcab/benchcab.py", line 59, in retrieve_cable_code
    G.main(**branch1)
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-22.04/lib/python3.9/site-packages/benchcab/get_cable.py", line 36, in main
    self.get_repo(name, trunk, share_branch)
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-22.04/lib/python3.9/site-packages/benchcab/get_cable.py", line 75, in get_repo
    output, error = p.communicate()
UnboundLocalError: local variable 'p' referenced before assignment
```

**Comment by ccarouge** [comment]
Fixed by pull request #3
