### ISSUE TITLE
FileNotFoundError when running benchcab v4.0.0

### ISSUE THREAD

**Issue by SeanBryan51** [CABLE-LSM/benchcab#267]
Running `benchcab run` with benchcab v4.0.0 fails to load resources from the package data directory and throws a FileNotFoundError:

```
$ benchcab run
Traceback (most recent call last):
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-24.01/bin/benchcab", line 10, in <module>
    sys.exit(main())
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-24.01/lib/python3.10/site-packages/benchcab/main.py", line 42, in main
    parse_and_dispatch(parser)
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-24.01/lib/python3.10/site-packages/benchcab/main.py", line 32, in parse_and_dispatch
    func(**args)
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-24.01/lib/python3.10/site-packages/benchcab/benchcab.py", line 368, in run
    self.checkout(config_path)
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-24.01/lib/python3.10/site-packages/benchcab/benchcab.py", line 221, in checkout
    config = self._get_config(config_path)
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-24.01/lib/python3.10/site-packages/benchcab/benchcab.py", line 136, in _get_config
    self._config = read_config(config_path)
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-24.01/lib/python3.10/site-packages/benchcab/config.py", line 169, in read_config
    validate_config(config)
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-24.01/lib/python3.10/site-packages/benchcab/config.py", line 58, in validate_config
    schema = bu.load_package_data("config-schema.yml")
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-24.01/lib/python3.10/site-packages/benchcab/utils/__init__.py", line 56, in load_package_data
    raw = pkgutil.get_data("benchcab", os.path.join("data", filename)).decode("utf-8")
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-24.01/lib/python3.10/pkgutil.py", line 639, in get_data
    return loader.get_data(resource_name)
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/hh5/public/apps/miniconda3/envs/analysis3-24.01/lib/python3.10/site-packages/benchcab/data/config-schema.yml'
```

To reproduce:

```
module load conda/analysis3-unstable
cd /scratch/$PROJECT/$USER
git clone git@github.com:CABLE-LSM/bench_example.git bench_example_tmp
cd bench_example_tmp
benchcab run
```

I have also reproduced the error in a custom conda environment.

**Comment by SeanBryan51** [comment]
The uploaded tarball for benchcab v4.0.0 is missing the `site-packages/benchcab/data` directory (see https://anaconda.org/accessnri/benchcab/files).

Building the conda package locally on Gadi and installing it seems to include the data directory which is strange. Perhaps something specific to the automated deployment is broken.

**Comment by SeanBryan51** [comment]
I've managed to reproduce and fix the error in my personal fork of benchcab by replacing the `include_package_data` option in setup.cfg with the [package_data](https://setuptools.pypa.io/en/latest/userguide/datafiles.html#package-data) option.

Hot fix release coming soon.

**Comment by SeanBryan51** [comment]
It might be possible that we are not testing the installed version of the package in our CI workflow. This is one of [the major disadvantages in using a flat layout](https://packaging.python.org/en/latest/discussions/src-layout-vs-flat-layout/). It would be interesting to see if the CI fails to find the data directory when switching to a src layout.
